name: Release
permissions:
  contents: write
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Install all private repositories as dependencies
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "TangibleInc/betterdash-module"
          path: "vendor/tangible/betterdash"
          token: ${{ secrets.TANGIBLE_PIPELINE_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "TangibleInc/betterlifter-module"
          path: "vendor/tangible/betterlifter"
          token: ${{ secrets.TANGIBLE_PIPELINE_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "TangibleInc/fields-pro"
          path: "vendor/tangible/fields-pro"
          token: ${{ secrets.TANGIBLE_PIPELINE_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: "TangibleInc/template-system-pro"
          token: ${{ secrets.TANGIBLE_PIPELINE_ACCESS_TOKEN }}
          path: "vendor/tangible/template-system-pro"
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Create archive
        run: bunx roll archive -y
      - name: Install pipeline
        run: mkdir -p publish && cd publish && git clone https://github.com/tangibleinc/pipeline
      - name: Add latest tag as needed
        uses: EndBug/latest-tag@latest
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      - name: Before release script
        run: bun run publish/pipeline/before-release.ts
      - name: Release tag
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          body_path: publish/release.md
          files: publish/*.zip
      - name: Release preview at latest commit
        uses: softprops/action-gh-release@v2
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          body_path: publish/release.md
          files: publish/*.zip
          tag_name: latest
          make_latest: true
      - name: After release script
        run: bun run publish/pipeline/after-release.ts
